sudo: false
cache:
    directories:
        - $HOME/.cabal
        - $HOME/.ghc
addons:
    apt:
        packages:
            - zlibc
language: nix
install:
- nix-env -i cabal-install
- nix-env -i ghc
- cabal update
- cabal install idris
- bash ci/fetch-deps
script:
- idris --testpkg test.ipkg
