language: haskell
sudo: false
ghc: 8.0.2

matrix:
    include:

        # Linux
        - env: TARGET=x86_64-unknown-linux-gnu

install:
- export PATH=$HOME/.cabal/bin:$PATH
- cabal update
- cabal install idris --dependencies-only
- travis_wait cabal install idris -j1
- git clone https://github.com/pheymann/specdris
- cd specdris
- idris --install specdris.ipkg
script:
- idris --testpkg test.pkg
