language: nix
sudo: false
#cache:
#    directories:
#        - $HOME/.cabal
#        - $HOME/.ghc
addons:
    apt:
        packages:
            - zlib1g-dev
install:
    #- nix-env -i stack
    #- nix-env -i ghc
    #- stack --no-terminal --install-ghc install idris
- nix-env -f "<nixpkgs>" -iA haskellPackages.idris
- bash ci/fetch-deps
script:
- idris --testpkg test.ipkg
