language: nix
sudo: false
#cache:
#    directories:
#        - $HOME/.cabal
#        - $HOME/.ghc
addons:
    apt:
        packages:
            - zlib1g-dev
install:
- nix-env -i cabal-install
- nix-env -i ghc
- cabal update
- cabal install ansi-wl-pprint-0.6.7.3
- cabal install idris
- bash ci/fetch-deps
script:
- idris --testpkg test.ipkg
