language: haskell
sudo: false
ghc: 8.0.2

matrix:
    include:

        # Linux
        - env: TARGET=x86_64-unknown-linux-gnu

        # OS X
        - env: TARGET=x86_64-apple-darwin
          os: osx

install:
- export PATH=$HOME/.cabal/bin:$PATH
- cabal update
- cabal install idris
- git clone https://github.com/pheymann/specdris
- cd specdris
- idris --install specdris.ipkg
script:
- idris --testpkg test.pkg
