---
sudo: false
language: default
cache:
  directories:
  - $HOME/.cabal
  - $HOME/.ghc
addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - libgmp3-dev
    - ghc-8.2.1
    - cabal-install-head

before_install:
- export PATH=$HOME/.cabal/bin:$PATH
- cabal update
- travis_wait cabal install idris
- git clone https://github.com/pheymann/specdris
- cd specdris/
- idris --install specdris.ipkg

install:
- idris --build recursion_schemes.ipkg

script:
- idris --testpkg test.ipkg
