language: nix
sudo: false
#cache:
#    directories:
#        - $HOME/.cabal
#        - $HOME/.ghc
addons:
    apt:
        packages:
            - zlib1g-dev
install:
- nix-env -i stack
- nix-env -i ghc
- cabal update
- find / -name zlib.h
- stack --no-terminal --install-ghc install idris
- bash ci/fetch-deps
script:
- idris --testpkg test.ipkg
